name: Backend CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소에서 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 환경 변수 설정
      - name: Set environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      # 3. application.yml 생성
      - name: Create application.yml
        run: |
          cat << EOF > application.yml
          spring:
            application:
              name: HouseHub Backend
            datasource:
              url: ${DB_URL}
              username: ${DB_USERNAME}
              password: '${DB_PASSWORD}'
              driver-class-name: com.mysql.cj.jdbc.Driver
            jpa:
              hibernate:
                ddl-auto: update
              properties:
                hibernate:
                  dialect: org.hibernate.dialect.MySQL8Dialect
            devtools:
              livereload:
                enabled: true
              restart:
                enabled: true
          server:
            port: 8080
          EOF

      # 4. Debug application.yml
      - name: Debug application.yml
        run: cat application.yml

      # 5. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 6. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew -i clean build --no-daemon

      # 빌드 결과 캐싱 (선택 사항)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

  deploy:
    runs-on: ubuntu-latest
    needs: build # build 작업이 성공해야 deploy 작업 실행
    if: github.ref == 'refs/heads/main' # main 브랜치로 push 될 때만 실행

    steps:
      # 1. GitHub 저장소에서 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_REPO }}:latest .

      # 3. Docker Hub 로그인
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Docker Hub에 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPO }}:latest

      # 5. Connect to EC2 and Deploy
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            # 작업 디렉토리 이동
            cd ~/househub

            # 기존 컨테이너 중지 및 제거
            docker-compose down

            # 최신 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_REPO }}:latest

            # 불필요한 이미지 삭제
            docker image prune -f

            # 컨테이너 실행
            docker-compose up -d --force-recreate