name: Backend CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. GitHub 저장소에서 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 17 설정 (Corretto 배포판)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      # 3. 환경 변수 설정
      - name: Set environment variables
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
          echo "REDIS_SESSION_TIMEOUT=1800" >> $GITHUB_ENV # 직접 설정
          echo "MAIL_HOST=smtp.example.com" >> $GITHUB_ENV # 직접 설정 또는 Secrets 사용
          echo "MAIL_PORT=587" >> $GITHUB_ENV # 직접 설정
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "ALIGO_API_KEY=${{ secrets.ALIGO_API_KEY }}" >> $GITHUB_ENV
          echo "ALIGO_ID=${{ secrets.ALIGO_ID }}" >> $GITHUB_ENV

      # 4. application.yml 생성
      - name: Create application.yml
        run: |
          # 디렉토리 생성 (명시적으로)
          mkdir -p src/main/resources
          
          cat << EOF > src/main/resources/application.yml
          spring:
            application:
              name: HouseHub Backend
            datasource:
              url: ${{ env.DB_URL }}  # 수정된 부분
              username: ${{ env.DB_USERNAME }}  # 수정된 부분
              password: '${{ env.DB_PASSWORD }}'  # 수정된 부분
              driver-class-name: com.mysql.cj.jdbc.Driver
            jpa:
              hibernate:
                ddl-auto: update
              properties:
                hibernate:
                  dialect: org.hibernate.dialect.MySQL8Dialect
            devtools:
              livereload:
                enabled: true
              restart:
                enabled: true
            data:
              redis:
                host: ${{ env.REDIS_HOST }} # Redis 서비스 이름과 동일하게 설정
                port: 6379 # Redis 기본 포트
            session:
              store-type: redis
              timeout: ${{ env.REDIS_SESSION_TIMEOUT }}
              redis:
                host: ${{ env.REDIS_HOST }}
                port: 6379
                namespace: "spring:session"
                flush-mode: on-save
            mail:
              host: ${{ env.MAIL_HOST }}
              port: ${{ env.MAIL_PORT }}
              username: ${{ env.MAIL_USERNAME }}
              password: ${{ env.MAIL_PASSWORD }}
              properties:
                mail:
                  smtp:
                    starttls:
                      enable: true
          springdoc:
            api-docs:
              enabled: true
            swagger-ui:
              enabled: true
              path: /swagger-ui.html
            paths-to-match: /**
          server:
            port: 8080
          logging:
            level:
              root: INFO # 기본 로그 레벨 설정
              com.househub.backend: DEBUG # 특정 패키지의 로그 레벨 설정
            pattern:
              console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # 로그 출력 패턴 설정    
          aligo:
            apikey: "${{ secrets.ALIGO_API_KEY }}"
            id: "${{ secrets.ALIGO_ID }}"   
               EOF
          
          # 파일 생성 확인
          ls -l src/main/resources/application.yml

      # 5. Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x gradlew && ./gradlew -i clean build --no-daemon
          chmod -R 777 build/libs
          ls -l build/libs
  deploy:
    runs-on: ubuntu-latest
    needs: build # build 작업이 성공해야 deploy 작업 실행
    if: github.ref == 'refs/heads/main' # main 브랜치로 push 될 때만 실행

    steps:
      # 1. GitHub 저장소에서 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -f Dockerfile -t ${{ secrets.DOCKERHUB_REPO }}:latest .

      # 3. Docker Hub 로그인
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Docker Hub에 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPO }}:latest

      # 5. Connect to EC2 and Deploy
      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            # 작업 디렉토리 이동
            cd ~/househub

            # 기존 컨테이너 중지 및 제거
            docker-compose down

            # 최신 이미지 가져오기
            docker pull ${{ secrets.DOCKERHUB_REPO }}:latest

            # 불필요한 이미지 삭제
            docker image prune -f

            # 컨테이너 실행
            docker-compose up -d --force-recreate